//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ch_nhac_cu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CTHoaDon
    {
        [DisplayName("Mã hóa đơn")]
        public string MaHD { get; set; }
        [DisplayName("Mã nhạc cụ")]
        public string MaNC { get; set; }
        [DisplayName("Số lượng bán")]
        public int SoLuongBan { get; set; }
        [DisplayName("Đơn giá bán")]
        public int DonGiaBan { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual NhacCu NhacCu { get; set; }
    }
}
