//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ch_nhac_cu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class LoaiNhacCu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiNhacCu()
        {
            this.NhacCus = new HashSet<NhacCu>();
        }
        [DisplayName("Mã loại nhạc cụ")]
        public string MaLoaiNC { get; set; }
        [DisplayName("Tên loại nhạc cụ")]
        public string TenLoaiNC { get; set; }
        [DisplayName("Ảnh loại nhạc cụ")]
        public string AnhLoaiNC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhacCu> NhacCus { get; set; }
    }
}
