//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ch_nhac_cu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class NhacCu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhacCu()
        {
            this.CTHoaDons = new HashSet<CTHoaDon>();
        }

        [DisplayName("Mã nhạc cụ")]
        public string MaNC { get; set; }
        [DisplayName("Tên nhạc cụ")]
        public string TenNC { get; set; }
        [DisplayName("Mô tả")]
        public string MoTa { get; set; }
        [DisplayName("Ảnh nhạc cụ")]
        public string AnhNC { get; set; }
        [DisplayName("Số lượng")]
        public int SoLuong { get; set; }
        [DisplayName("Thời gian bảo hành")]
        public string ThoiGianBaoHanh { get; set; }
        [DisplayName("Đơn giá")]
        public int DonGia { get; set; }
        [DisplayName("Loại nhạc cụ")]
        public string MaLoaiNC { get; set; }
        [DisplayName("Nhà cung cấp")]
        public string MaNCC { get; set; }
        [DisplayName("Hãng sản xuất")]
        public string MaHSX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDon> CTHoaDons { get; set; }
        public virtual HangSanXuat HangSanXuat { get; set; }
        public virtual LoaiNhacCu LoaiNhacCu { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
