//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ch_nhac_cu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLCHNCEntities : DbContext
    {
        public QLCHNCEntities()
            : base("name=QLCHNCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<CTHoaDon> CTHoaDons { get; set; }
        public virtual DbSet<HangSanXuat> HangSanXuats { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiNhacCu> LoaiNhacCus { get; set; }
        public virtual DbSet<NhacCu> NhacCus { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<ThamSo> ThamSoes { get; set; }
    
        public virtual ObjectResult<GetSalesReport_Result> GetSalesReport(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSalesReport_Result>("GetSalesReport", fromDateParameter, toDateParameter);
        }
    
        public virtual int NhacCu_TimKiem(string maNC, string tenNC, string thoiGianBaoHanh, string donGiaMin, string donGiaMax, string maLoaiNC, string maNCC, string maHSX, string soLuong)
        {
            var maNCParameter = maNC != null ?
                new ObjectParameter("MaNC", maNC) :
                new ObjectParameter("MaNC", typeof(string));
    
            var tenNCParameter = tenNC != null ?
                new ObjectParameter("TenNC", tenNC) :
                new ObjectParameter("TenNC", typeof(string));
    
            var thoiGianBaoHanhParameter = thoiGianBaoHanh != null ?
                new ObjectParameter("ThoiGianBaoHanh", thoiGianBaoHanh) :
                new ObjectParameter("ThoiGianBaoHanh", typeof(string));
    
            var donGiaMinParameter = donGiaMin != null ?
                new ObjectParameter("DonGiaMin", donGiaMin) :
                new ObjectParameter("DonGiaMin", typeof(string));
    
            var donGiaMaxParameter = donGiaMax != null ?
                new ObjectParameter("DonGiaMax", donGiaMax) :
                new ObjectParameter("DonGiaMax", typeof(string));
    
            var maLoaiNCParameter = maLoaiNC != null ?
                new ObjectParameter("MaLoaiNC", maLoaiNC) :
                new ObjectParameter("MaLoaiNC", typeof(string));
    
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var maHSXParameter = maHSX != null ?
                new ObjectParameter("MaHSX", maHSX) :
                new ObjectParameter("MaHSX", typeof(string));
    
            var soLuongParameter = soLuong != null ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhacCu_TimKiem", maNCParameter, tenNCParameter, thoiGianBaoHanhParameter, donGiaMinParameter, donGiaMaxParameter, maLoaiNCParameter, maNCCParameter, maHSXParameter, soLuongParameter);
        }
    
        public virtual int NhaCungCap_TimKiem(string maNCC, string tenNCC, string sDT, string email, string diaChi)
        {
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var tenNCCParameter = tenNCC != null ?
                new ObjectParameter("TenNCC", tenNCC) :
                new ObjectParameter("TenNCC", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhaCungCap_TimKiem", maNCCParameter, tenNCCParameter, sDTParameter, emailParameter, diaChiParameter);
        }
    
        public virtual int HangSanXuat_TimKiem(string maHSX, string tenHSX, string diaChi, string sDT)
        {
            var maHSXParameter = maHSX != null ?
                new ObjectParameter("MaHSX", maHSX) :
                new ObjectParameter("MaHSX", typeof(string));
    
            var tenHSXParameter = tenHSX != null ?
                new ObjectParameter("TenHSX", tenHSX) :
                new ObjectParameter("TenHSX", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HangSanXuat_TimKiem", maHSXParameter, tenHSXParameter, diaChiParameter, sDTParameter);
        }
    
        public virtual int KhachHang_TimKiem(string maKH, string hoTenKH, string sDT, string email, string diaChi, string taiKhoan)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var hoTenKHParameter = hoTenKH != null ?
                new ObjectParameter("HoTenKH", hoTenKH) :
                new ObjectParameter("HoTenKH", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KhachHang_TimKiem", maKHParameter, hoTenKHParameter, sDTParameter, emailParameter, diaChiParameter, taiKhoanParameter);
        }
    
        public virtual int LoaiNhacCu_TimKiem(string maLoaiNC, string tenLoaiNC)
        {
            var maLoaiNCParameter = maLoaiNC != null ?
                new ObjectParameter("MaLoaiNC", maLoaiNC) :
                new ObjectParameter("MaLoaiNC", typeof(string));
    
            var tenLoaiNCParameter = tenLoaiNC != null ?
                new ObjectParameter("TenLoaiNC", tenLoaiNC) :
                new ObjectParameter("TenLoaiNC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LoaiNhacCu_TimKiem", maLoaiNCParameter, tenLoaiNCParameter);
        }
    
        public virtual int NhanVien_TimKiem(string maNV, string hoTenNV, string sDT, string email, string diaChi, string tenDN, string maCV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoTenNVParameter = hoTenNV != null ?
                new ObjectParameter("HoTenNV", hoTenNV) :
                new ObjectParameter("HoTenNV", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var tenDNParameter = tenDN != null ?
                new ObjectParameter("TenDN", tenDN) :
                new ObjectParameter("TenDN", typeof(string));
    
            var maCVParameter = maCV != null ?
                new ObjectParameter("MaCV", maCV) :
                new ObjectParameter("MaCV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhanVien_TimKiem", maNVParameter, hoTenNVParameter, sDTParameter, emailParameter, diaChiParameter, tenDNParameter, maCVParameter);
        }
    }
}
